apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagpkubernetesdockerdemo-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagpkubernetesdockerdemo-api
  template:
    metadata:
      labels:
        app: nagpkubernetesdockerdemo-api
    spec:
      containers:
        - name: nagpkubernetesdockerdemo-api
          image: meghaprasadnagarro/nagpkubernetesdockerdemo:dev
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: database_host     
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mysql_database 
          ports:
            - containerPort: 5932    
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api
spec:
  selector:
    app: nagpkubernetesdockerdemo-api
  ports:
    - protocol: TCP
      port: 5932
      targetPort: 5932
  type: LoadBalancer
